// src/lib/emojisToCurrency.ts
export const emojisToCurrency = [
	{ currency: 'mnt', emoji: '🇲🇳', country: 'Mongolia' },
	{ currency: 'usd', emoji: '🇺🇸', country: 'United States' },
	{ currency: 'cny', emoji: '🇨🇳', country: 'China' },
	{ currency: 'eur', emoji: '🇪🇺', country: 'European Union' },
	{ currency: 'inr', emoji: '🇮🇳', country: 'India' },
	{ currency: 'jpy', emoji: '🇯🇵', country: 'Japan' },
	{ currency: 'gbp', emoji: '🇬🇧', country: 'United Kingdom' },
	{ currency: 'cad', emoji: '🇨🇦', country: 'Canada' },
	{ currency: 'chf', emoji: '🇨🇭', country: 'Switzerland' },
	{ currency: 'sek', emoji: '🇸🇪', country: 'Sweden' },
	{ currency: 'bgn', emoji: '🇧🇬', country: 'Bulgaria' },
	{ currency: 'huf', emoji: '🇭🇺', country: 'Hungary' },
	{ currency: 'krw', emoji: '🇰🇷', country: 'South Korea' },
	{ currency: 'egp', emoji: '🇪🇬', country: 'Egypt' },
	{ currency: 'hkd', emoji: '🇭🇰', country: 'Hong Kong' },
	{ currency: 'rub', emoji: '🇷🇺', country: 'Russia' },
	{ currency: 'kzt', emoji: '🇰🇿', country: 'Kazakhstan' },
	{ currency: 'kpw', emoji: '🇰🇵', country: 'North Korea' },
	{ currency: 'aud', emoji: '🇦🇺', country: 'Australia' },
	{ currency: 'czk', emoji: '🇨🇿', country: 'Czech Republic' },
	{ currency: 'twd', emoji: '🇹🇼', country: 'Taiwan' },
	{ currency: 'thb', emoji: '🇹🇭', country: 'Thailand' },
	{ currency: 'idr', emoji: '🇮🇩', country: 'Indonesia' },
	{ currency: 'myr', emoji: '🇲🇾', country: 'Malaysia' },
	{ currency: 'sgd', emoji: '🇸🇬', country: 'Singapore' },
	{ currency: 'aed', emoji: '🇦🇪', country: 'United Arab Emirates' },
	{ currency: 'kwd', emoji: '🇰🇼', country: 'Kuwait' },
	{ currency: 'nzd', emoji: '🇳🇿', country: 'New Zealand' },
	{ currency: 'dkk', emoji: '🇩🇰', country: 'Denmark' },
	{ currency: 'pln', emoji: '🇵🇱', country: 'Poland' },
	{ currency: 'uah', emoji: '🇺🇦', country: 'Ukraine' },
	{ currency: 'nok', emoji: '🇳🇴', country: 'Norway' },
	{ currency: 'npr', emoji: '🇳🇵', country: 'Nepal' },
	{ currency: 'zar', emoji: '🇿🇦', country: 'South Africa' },
	{ currency: 'try', emoji: '🇹🇷', country: 'Türkiye' },
	{ currency: 'vnd', emoji: '🇻🇳', country: 'Vietnam' },
	{ currency: 'brl', emoji: '🇧🇷', country: 'Brazil' },
	{ currency: 'mxn', emoji: '🇲🇽', country: 'Mexico' },
	{ currency: 'ars', emoji: '🇦🇷', country: 'Argentina' },
	{ currency: 'clp', emoji: '🇨🇱', country: 'Chile' },
	{ currency: 'cop', emoji: '🇨🇴', country: 'Colombia' },
	{ currency: 'php', emoji: '🇵🇭', country: 'Philippines' },
	{ currency: 'ngn', emoji: '🇳🇬', country: 'Nigeria' },
	{ currency: 'ils', emoji: '🇮🇱', country: 'Israel' },
	{ currency: 'sar', emoji: '🇸🇦', country: 'Saudi Arabia' },
	{ currency: 'qar', emoji: '🇶🇦', country: 'Qatar' },
	{ currency: 'xau', emoji: '⚜️', country: 'Gold' },
	{ currency: 'xag', emoji: '🪙', country: 'Silver' }
];
