// src/lib/emojisToCurrency.ts
export const emojisToCurrency = [
	{ currency: 'mnt', countryEmoji: '🇲🇳', currencyEmoji: '🇲🇳', country: 'Mongolia' },
	{ currency: 'usd', countryEmoji: '🇺🇸', currencyEmoji: '🇺🇸', country: 'United States' },
	{ currency: 'cny', countryEmoji: '🇨🇳', currencyEmoji: '🇨🇳', country: 'China' },
	{ currency: 'eur', countryEmoji: '🇪🇺', currencyEmoji: '🇪🇺', country: 'European Union' },
	{ currency: 'inr', countryEmoji: '🇮🇳', currencyEmoji: '🇮🇳', country: 'India' },
	{ currency: 'jpy', countryEmoji: '🇯🇵', currencyEmoji: '🇯🇵', country: 'Japan' },
	{ currency: 'gbp', countryEmoji: '🇬🇧', currencyEmoji: '🇬🇧', country: 'United Kingdom' },
	{ currency: 'cad', countryEmoji: '🇨🇦', currencyEmoji: '🇨🇦', country: 'Canada' },
	{ currency: 'chf', countryEmoji: '🇨🇭', currencyEmoji: '🇨🇭', country: 'Switzerland' },
	{ currency: 'sek', countryEmoji: '🇸🇪', currencyEmoji: '🇸🇪', country: 'Sweden' },
	{ currency: 'bgn', countryEmoji: '🇧🇬', currencyEmoji: '🇧🇬', country: 'Bulgaria' },
	{ currency: 'huf', countryEmoji: '🇭🇺', currencyEmoji: '🇭🇺', country: 'Hungary' },
	{ currency: 'krw', countryEmoji: '🇰🇷', currencyEmoji: '🇰🇷', country: 'South Korea' },
	{ currency: 'egp', countryEmoji: '🇪🇬', currencyEmoji: '🇪🇬', country: 'Egypt' },
	{ currency: 'hkd', countryEmoji: '🇭🇰', currencyEmoji: '🇭🇰', country: 'Hong Kong' },
	{ currency: 'rub', countryEmoji: '🇷🇺', currencyEmoji: '🇷🇺', country: 'Russia' },
	{ currency: 'kzt', countryEmoji: '🇰🇿', currencyEmoji: '🇰🇿', country: 'Kazakhstan' },
	{ currency: 'kpw', countryEmoji: '🇰🇵', currencyEmoji: '🇰🇵', country: 'North Korea' },
	{ currency: 'aud', countryEmoji: '🇦🇺', currencyEmoji: '🇦🇺', country: 'Australia' },
	{ currency: 'czk', countryEmoji: '🇨🇿', currencyEmoji: '🇨🇿', country: 'Czech Republic' },
	{ currency: 'twd', countryEmoji: '🇹🇼', currencyEmoji: '🇹🇼', country: 'Taiwan' },
	{ currency: 'thb', countryEmoji: '🇹🇭', currencyEmoji: '🇹🇭', country: 'Thailand' },
	{ currency: 'idr', countryEmoji: '🇮🇩', currencyEmoji: '🇮🇩', country: 'Indonesia' },
	{ currency: 'myr', countryEmoji: '🇲🇾', currencyEmoji: '🇲🇾', country: 'Malaysia' },
	{ currency: 'sgd', countryEmoji: '🇸🇬', currencyEmoji: '🇸🇬', country: 'Singapore' },
	{ currency: 'aed', countryEmoji: '🇦🇪', currencyEmoji: '🇦🇪', country: 'United Arab Emirates' },
	{ currency: 'kwd', countryEmoji: '🇰🇼', currencyEmoji: '🇰🇼', country: 'Kuwait' },
	{ currency: 'nzd', countryEmoji: '🇳🇿', currencyEmoji: '🇳🇿', country: 'New Zealand' },
	{ currency: 'dkk', countryEmoji: '🇩🇰', currencyEmoji: '🇩🇰', country: 'Denmark' },
	{ currency: 'pln', countryEmoji: '🇵🇱', currencyEmoji: '🇵🇱', country: 'Poland' },
	{ currency: 'uah', countryEmoji: '🇺🇦', currencyEmoji: '🇺🇦', country: 'Ukraine' },
	{ currency: 'nok', countryEmoji: '🇳🇴', currencyEmoji: '🇳🇴', country: 'Norway' },
	{ currency: 'npr', countryEmoji: '🇳🇵', currencyEmoji: '🇳🇵', country: 'Nepal' },
	{ currency: 'zar', countryEmoji: '🇿🇦', currencyEmoji: '🇿🇦', country: 'South Africa' },
	{ currency: 'try', countryEmoji: '🇹🇷', currencyEmoji: '🇹🇷', country: 'Türkiye' },
	{ currency: 'vnd', countryEmoji: '🇻🇳', currencyEmoji: '🇻🇳', country: 'Vietnam' },
	{ currency: 'brl', countryEmoji: '🇧🇷', currencyEmoji: '🇧🇷', country: 'Brazil' },
	{ currency: 'mxn', countryEmoji: '🇲🇽', currencyEmoji: '🇲🇽', country: 'Mexico' },
	{ currency: 'ars', countryEmoji: '🇦🇷', currencyEmoji: '🇦🇷', country: 'Argentina' },
	{ currency: 'clp', countryEmoji: '🇨🇱', currencyEmoji: '🇨🇱', country: 'Chile' },
	{ currency: 'cop', countryEmoji: '🇨🇴', currencyEmoji: '🇨🇴', country: 'Colombia' },
	{ currency: 'php', countryEmoji: '🇵🇭', currencyEmoji: '🇵🇭', country: 'Philippines' },
	{ currency: 'ngn', countryEmoji: '🇳🇬', currencyEmoji: '🇳🇬', country: 'Nigeria' },
	{ currency: 'ils', countryEmoji: '🇮🇱', currencyEmoji: '🇮🇱', country: 'Israel' },
	{ currency: 'sar', countryEmoji: '🇸🇦', currencyEmoji: '🇸🇦', country: 'Saudi Arabia' },
	{ currency: 'qar', countryEmoji: '🇶🇦', currencyEmoji: '🇶🇦', country: 'Qatar' },
	{ currency: 'xau', countryEmoji: '⚜️', currencyEmoji: '⚜️', country: 'Gold' },
	{ currency: 'xag', countryEmoji: '🪙', currencyEmoji: '🪙', country: 'Silver' }
];
